package com.zyb.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-22T11:37:19.105+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://impl.service.zyb.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://impl.service.zyb.com/", className = "com.zyb.service.impl.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://impl.service.zyb.com/", className = "com.zyb.service.impl.AddUserResponse")
    @WebResult(name = "reValMessage", targetNamespace = "")
    public String addUser(

            @WebParam(name = "name", targetNamespace = "")
                    String name,
            @WebParam(name = "age", targetNamespace = "")
                    int age
    );
}
